project:
  type: book
  post-render:
    - bash ./scripts/build-glossary.sh

resources:
  - glossary.json
  - scripts/*

extensions:
  - glossary
  - headings
  
format:
  html:
    theme:
      - flatly
    css:
      - styles/glossary-tooltips.css
      - styles/custom-callouts.css
    include-after-body:
      - scripts/inject-custom.html
    include-in-header: mathjax-macros.html
    html-math-method: mathjax
    mermaid:
      theme: neutral

  pdf: 
    include-in-header: macros.tex

book:
  title: "DHS Algebra 1"
  author: "Andy Ross"
  favicon: images/logo.png
  image: images/logo.png
  search: true
  
  navbar:
    search: true

  sidebar:
    search: true
    logo: images/logo.png
    collapse-level: 1
 
  chapters:
    - file: index.md
    
    - part: "Unit 1: Foundations"
      chapters:
        - file: chapters/Unit_1/index.qmd
        - file: chapters/Unit_1/1.1_Integers_&_Number_Lines.qmd
        - file: chapters/Unit_1/1.2_Factors_Multiples_&_Prime_Factorization.qmd
        - file: chapters/Unit_1/1.3_GCF_&_Simplifying_Fractions.qmd
        - file: chapters/Unit_1/1.4_Fractions_Decimals_&_Percents.qmd
        - file: chapters/Unit_1/1.5_Multiply_Divide_&_Compare_Fractions.qmd
        - file: chapters/Unit_1/1.6_Adding_and_Subtracting_Fractions.qmd
        - file: chapters/Unit_1/1.7_Solving_Problems_with_Fractions_Decimals_and_Percents.qmd
        - file: chapters/Unit_1/1.8_Order_of_Operations.qmd
        - file: chapters/Unit_1/Review.qmd

    - part: "Unit 2: Algebraic Expressions"
      chapters:
        - file: chapters/Unit_2/index.qmd
        - file: chapters/Unit_2/2.1_Expressions_and_Their_Parts.qmd
        - file: chapters/Unit_2/2.2_Evaluating_Expressions.qmd
        - file: chapters/Unit_2/2.3_Combining_Like_Terms.qmd
        - file: chapters/Unit_2/2.4_The_Distributive_Property.qmd
        - file: chapters/Unit_2/2.5_Inputs_Outputs_and_Functions.qmd
        - file: chapters/Unit_2/2.6_Equivalent_Expressions.qmd
        - file: chapters/Unit_2/Review.qmd

    - part: "Unit 3: Solving Linear Equations"
      chapters:
        - file: chapters/Unit_3/index.md
        - file: chapters/Unit_3/3.1_Solving_One-Step_Equations.qmd
        - file: chapters/Unit_3/3.2_Solving_Two-Step_Equations.qmd
        - file: chapters/Unit_3/3.3_Multi-Step_Equations_with_Distribution.qmd
        - file: chapters/Unit_3/3.4_Equations_with_Variables_on_Both_Sides.qmd
        - file: chapters/Unit_3/3.5_Equations_With_No_or_Infinite_Solutions.qmd
        - file: chapters/Unit_3/3.6_Solving_Inequalities.qmd
        - file: chapters/Unit_3/3.7_Solving_Literal_Equations.qmd
        - file: chapters/Unit_3/Review.qmd

    - part: "Unit 4: Linear Functions & Graphs"
      chapters:
        - file: chapters/Unit_4/index.qmd
        - file: chapters/Unit_4/4.1_Graphing_Function_Rules.qmd
        - file: chapters/Unit_4/4.2_Understanding_Slope.qmd
        - file: chapters/Unit_4/4.3_The_Equation_of_a_Line.qmd
        - file: chapters/Unit_4/4.4_Writing_Linear_Equations.qmd
        - file: chapters/Unit_4/4.5_Systems_of_Equations.qmd
        - file: chapters/Unit_4/4.6_Linear_Models_in_the_Real_World.qmd
        - file: chapters/Unit_4/4.7_Graphing_Linear_Inequalities.qmd
        - file: chapters/Unit_4/Review.qmd

    - part: "Unit 5: Exponents & Polynomials"
      chapters:
        - file: chapters/Unit_5/index.qmd
        - file: chapters/Unit_5/5.1_Exponent_Rules.qmd
        - file: chapters/Unit_5/5.2_Introduction_to_Polynomials.qmd
        - file: chapters/Unit_5/5.3_Multiplying_Polynomials.qmd
        - file: chapters/Unit_5/5.4_Factoring_Polynomials.qmd
        - file: chapters/Unit_5/Review.qmd

    - part: "Unit 6: Quadratic Equations & Functions"
      chapters:
        - file: chapters/Unit_6/index.qmd
        - file: chapters/Unit_6/6.1_Introduction_to_Quadratic_Functions.qmd
        - file: chapters/Unit_6/6.2_Forms_of_Quadratic_Equations.qmd
        - file: chapters/Unit_6/6.3_Solving_Quadratic_Equations_by_Factoring.qmd
        - file: chapters/Unit_6/6.4_Completing_the_Square.qmd
        - file: chapters/Unit_6/6.5_The_Quadratic_Formula.qmd
        - file: chapters/Unit_6/6.6_Graphing_Quadratic_Functions.qmd
        - file: chapters/Unit_6/Review.qmd

    - part: "Interactive Learning"
      chapters:
        - file: chapters/Interactive/index.qmd
        - file: chapters/Interactive/Unit_4/understanding_slope.qmd
        - file: chapters/Interactive/Unit_4/exploring_slope_intercept_form.qmd
        - file: chapters/Interactive/Unit_4/intro_to_correlation.qmd
        - file: chapters/Interactive/Unit_4/slope_intercept_form_game.qmd

    - part: "Supplemental"
      chapters:
        - file: chapters/Supplemental/index.qmd
        - file: chapters/Supplemental/math_games_and_puzzles/index.md
        - file: chapters/Supplemental/worksheets/index.qmd
        - file: chapters/Supplemental/challenge_solutions.qmd

    - file: resources.qmd
    - file: glossary.qmd