project:
  type: book
  post-render:
    - ./scripts/build-glossary.sh

resources:
  - glossary.json
  - scripts/*

extensions:
  - glossary
  
format:
  html:
    theme:
      - flatly
    css:
      - styles/glossary-tooltips.css
      - styles/custom-callouts.css
    include-after-body:
      - scripts/inject-custom.html
    mermaid:
      theme: neutral

  pdf: 
    include-in-header:
      text: |
        \usepackage{cancel}
        \usepackage{xcolor}
  
website:
  favicon: images/logo.png
  
book:
  title: "DHS Algebra 1"
  author: "Andy Ross"
  favicon: images/logo.png
  image: images/logo.png
  search: true
  
  navbar:
    search: true

  sidebar:
    search: true
    logo: images/logo.png
    collapse-level: 1
 
  chapters:
    - file: index.md
    
    - part: "Unit 1: Foundations"
      chapters:
        - file: chapters/Unit_1/index.qmd
        - file: chapters/Unit_1/1.1_Integers_&_Number_Lines.qmd
        - file: chapters/Unit_1/1.2_Factors_Multiples_&_Prime_Factorization.qmd
        - file: chapters/Unit_1/1.3_GCF_&_Simplifying_Fractions.qmd
        - file: chapters/Unit_1/1.4_Fractions_Decimals_&_Percents.qmd
        - file: chapters/Unit_1/1.5_Multiply_Divide_&_Compare_Fractions.qmd
        - file: chapters/Unit_1/1.6_Solving_Problems_with_Fractions_Decimals_and_Percents.qmd
        - file: chapters/Unit_1/1.7_Order_of_Operations.qmd

    - part: "Unit 2: Algebraic Expressions"
      chapters:
        - file: chapters/Unit_2/index.md
        - file: chapters/Unit_2/2.1_Evaluating_Expressions.md
        - file: chapters/Unit_2/2.2_Inputs,_Outputs_&_Function_Machines_(Intro).md

    - part: "Unit 3: Solving Equations"
      chapters:
        - file: chapters/Unit_3/index.md
        - file: chapters/Unit_3/3.1_Solving_One-Step_&_Two-Step_Equations.md
        - file: chapters/Unit_3/3.2_Multi-Step_Equations_with_Distribution.md
        - file: chapters/Unit_3/3.3_Equations_with_Variables_on_Both_Sides.md
        - file: chapters/Unit_3/3.4_No_Solution_vs._Infinite_Solutions.md
        - file: chapters/Unit_3/3.5_Writing_Equations_from_Real-Life_Contexts.md
        - file: chapters/Unit_3/3.6_Solving_with_Tables,_Graphs_&_Rules_(Function_tie-in).md

    - part: "Unit 4: Graphs and Patterns"
      chapters:
        - file: chapters/Unit_4/index.md
        - file: chapters/Unit_4/4.1_Graphing_Expressions_with_Tables.md
        - file: chapters/Unit_4/4.2_Interpreting_Graphs_in_Context.md
        - file: chapters/Unit_4/4.3_Arithmetic_vs._Geometric_Patterns.md
        - file: chapters/Unit_4/4.4_Linear_Modeling_&_Rate_of_Change.md
        - file: chapters/Unit_4/4.5_Estimating_and_Checking_with_Graphs.md

    - part: "Unit 5: Inequalities"
      chapters:
        - file: chapters/Unit_5/index.md
        - file: chapters/Unit_5/5.1_One-_and_Two-Step_Inequalities.md
        - file: chapters/Unit_5/5.2_Graphing_on_a_Number_Line.md
        - file: chapters/Unit_5/5.3_Writing_Inequalities_from_Situations.md
        - file: chapters/Unit_5/5.4_Interpreting_Graphs_with_Constraints.md
        - file: chapters/Unit_5/5.5_Compound_Inequalities_(Optional).md

    - part: "Unit 6: Linear Relationships"
      chapters:
        - file: chapters/Unit_6/index.md
        - file: chapters/Unit_6/6.1_The_Coordinate_Plane_&_Graphing_from_Tables.md
        - file: chapters/Unit_6/6.2_Understanding_Slope_as_Rate_of_Change.md
        - file: chapters/Unit_6/6.3_Slope-Intercept_Form.md
        - file: chapters/Unit_6/6.4_Writing_Equations_from_Graphs_or_Words.md
        - file: chapters/Unit_6/6.5_Comparing_Linear_Models_from_Graphs_or_Data.md
        - file: chapters/Unit_6/6.6_Applications__Cost,_Speed,_Growth.md

    - part: "Unit 7: Exponents and Powers"
      chapters:
        - file: chapters/Unit_7/index.md
        - file: chapters/Unit_7/7.1_Multiplying_with_Exponents.md
        - file: chapters/Unit_7/7.2_Dividing_with_Exponents.md
        - file: chapters/Unit_7/7.3_Power_of_a_Power.md
        - file: chapters/Unit_7/7.4_Zero_and_Negative_Exponents_(Intro_only).md

    - part: "Unit 8: Quadratic Thinking"
      chapters:
        - file: chapters/Unit_8/index.md
        - file: chapters/Unit_8/8.1_Recognizing_Quadratic_Equations.md
        - file: chapters/Unit_8/8.2_Factoring_Simple_Quadratics.md
        - file: chapters/Unit_8/8.3_Solving_by_Factoring.md
        - file: chapters/Unit_8/8.4_The_Quadratic_Formula_(Intro).md
        - file: chapters/Unit_8/8.5_Graphing_Parabolas_by_Table_&_Comparing_with_Linear.md

    - part: "Unit 9: Systems of Equations"
      chapters:
        - file: chapters/Unit_9/index.md
        - file: chapters/Unit_9/9.1_What_Is_a_System.md
        - file: chapters/Unit_9/9.2_Solving_by_Graphing.md
        - file: chapters/Unit_9/9.3_Substitution_Method_(Optional).md
        - file: chapters/Unit_9/9.4_Word_Problems_with_Systems.md

    - part: "Unit 10: Cumulative Review and Projects"
      chapters:
        - file: chapters/Unit_10/index.md
        - file: chapters/Unit_10/10.1_Vocabulary_Review.md
        - file: chapters/Unit_10/10.2_Real-World_Projects_(Graphs_+_Tables_+_Equations).md
        - file: chapters/Unit_10/10.3_Group_Presentations_or_Visual_Reports.md
        - file: chapters/Unit_10/10.4_Final_Assessment_or_EOC_Practice.md

    - part: "Supplemental"
      chapters:
        - file: chapters/Supplemental/index.md
        - file: chapters/Supplemental/math_games_and_puzzles/index.md

    - file: resources.qmd
    - file: glossary.qmd