# Resources {.unnumbered}

Looking for extra support as you learn Algebra? Below you'l find helpful links to additional study materials and downloadable cheat sheets!

***

### Multiplication Facts Table

This is a table of multiplication facts for integers from 1 to 12. Being too reliant on a calculator for basic multiplication facts will slow you down and make Algebra more difficult. Try working with this sheet instead. If you can memorize these facts, your math experience will dramatically improve!

[Download Table](/resources/MultiplicationFacts.pdf)

***

### Factor Chart

Need help finding all the factor pairs of a number? This chart lists every {{< glink composite number >}} from 1 to 147 and lists all {{< glink prime numbers >}} up to 200. For each number, you'll see a list of its factor pairs.

[Download Chart](/resources/FactorChart.pdf)

***

### Words to Expressions

Translating from words to algebraic expressions can be a challenge. This chart lists many of the common words and phrases and shows how they are represented in expressions.

[Download Chart](/resources/KeywordTranslations.pdf)

***

