# Index {.unnumbered}

## Unit 1 - Algebra Foundations

#### [Prime Factorization Game](Unit_1/prime_factorization_game.qmd)

Build factor trees to find the prime factorization of numbers.

## Unit 2 - Algebraic Expressions

Coming Soon

## Unit 3 - Solving Linear Equations

Coming Soon


## Unit 4 - Linear Functions & Graphs

#### [Slope Explorer](Unit_4/understanding_slope.qmd)

Drag points around the grid to see how slope changes with point position.

#### [Slope-Intercept Form Investigation](Unit_4/exploring_slope_intercept_form.qmd)

Move the slope and y-intercept sliders to see how lines change based on their equation.

#### [Line Matching Game](Unit_4/slope_intercept_form_game.qmd)

Try to get a high score matching slopes and intercepts in this fast-paced matching game.

#### [Intro to Correlation](Unit_4/intro_to_correlation.qmd)

Move the slider to see the effect of different correlation values.

## Unit 5 - Exponents & Polynomials

Coming Soon

## Unit 6 - Quadratic Equations & Functions

#### [Vertex Form Explorer](Unit_6/vertex_form_explorer.qmd)

Move sliders to see how parameters $a$, $h$, and $k$ effect the shape and location of a parabola.