name: Mirror site to Work (diagnostic)

on:
  workflow_dispatch:
    inputs:
      source_ref:
        description: "Source branch or tag in personal repo"
        required: false
        default: "gh-pages"
      dest_branch:
        description: "Destination branch in work repo"
        required: false
        default: "prod"

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs / env
        run: |
          echo "SOURCE_REF=${{ inputs.source_ref }}"
          echo "DEST_BRANCH=${{ inputs.dest_branch }}"
          echo "WORK_OWNER=${{ secrets.WORK_OWNER }}"
          echo "WORK_REPO=${{ secrets.WORK_REPO }}"
          echo "Has WORK_TOKEN? ${{ secrets.WORK_TOKEN != '' }}"

      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_ref }}
          fetch-depth: 0

      - name: Verify source ref exists
        run: |
          git rev-parse --abbrev-ref HEAD
          echo "Listing local branches:"
          git branch -a
          echo "Top-level files:"
          ls -la

      - name: Test auth to work repo (read)
        run: |
          set -e
          echo "Running ls-remote on work repo to verify token and repo path..."
          git ls-remote https://${{ secrets.WORK_TOKEN }}@github.com/${{ secrets.WORK_OWNER }}/${{ secrets.WORK_REPO }}.git

      - name: Push to work repo
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add work https://${{ secrets.WORK_TOKEN }}@github.com/${{ secrets.WORK_OWNER }}/${{ secrets.WORK_REPO }}.git
          echo "Pushing ${{ inputs.source_ref }} -> ${{ inputs.dest_branch }} (force)…"
          git push --force work ${{ inputs.source_ref }}:${{ inputs.dest_branch }}
