name: Mirror site to Work (diagnostic)

on:
  workflow_dispatch:
    inputs:
      source_ref:
        description: "Source branch or tag in personal repo"
        required: false
        default: "gh-pages"
      dest_branch:
        description: "Destination branch in work repo"
        required: false
        default: "prod"

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs / env
        run: |
          echo "SOURCE_REF=${{ inputs.source_ref }}"
          echo "DEST_BRANCH=${{ inputs.dest_branch }}"
          echo "WORK_OWNER=${{ secrets.WORK_OWNER }}"
          echo "WORK_REPO=${{ secrets.WORK_REPO }}"
          echo "Has WORK_TOKEN? ${{_
